version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
    volumes:
      - ./backend:/app
    command: npm start  # ajusta según tu proyecto

  front-web:
    build:
      context: ./front-web
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    volumes:
      - ./front-web:/app
    command: npm run dev  # ajusta según el framework (vite, react-scripts, etc.)

  admin-web:
    build:
      context: ./admin-web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./admin-web:/app
    command: npm run dev  # ajusta según el framework