services:
  mysql:
    image: mysql:8
    container_name: calmatec_db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: tesis_db
    volumes:
      - db_data:/var/lib/mysql
      - ./BACKEND/src/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - calmatec_net

  backend:
    build:
      context: ./BACKEND
      dockerfile: Dockerfile
    container_name: calmatec_backend
    ports:
      - "8080:8080"   # Asumiendo que PORT está en tu .env
    env_file:
      - ./BACKEND/.env
    depends_on:
      - mysql
    networks:
      - calmatec_net

  frontend-web:
    build:
      context: ./FRONT-WEB
      dockerfile: Dockerfile
    container_name: frontend_web
    ports:
      - "8081:80" 
    networks:
      - calmatec_net

  admin-frontend:
    build:
      context: ./ADMIN-WEB
      dockerfile: Dockerfile
    container_name: admin_frontend
    ports:
      - "8082:80"
    networks:
      - calmatec_net

volumes:
  db_data:

networks:
  calmatec_net: