-- MySQL Script generated by MySQL Workbench
-- Fri May 16 20:55:59 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema tesis_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tesis_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tesis_db` DEFAULT CHARACTER SET utf8mb3 ;
USE `tesis_db` ;

-- -----------------------------------------------------
-- Table `tesis_db`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tesis_db`.`rol` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `tesis_db`.`multimedia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tesis_db`.`multimedia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(255) NULL DEFAULT NULL,
  `fecha` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `tesis_db`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tesis_db`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `correo` VARCHAR(50) NULL DEFAULT NULL,
  `apellido` VARCHAR(45) NULL DEFAULT NULL,
  `fecha_registro` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `rol_id` INT NOT NULL,
  `multimedia_id` INT NULL,
  `contrasena` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`correo` ASC) VISIBLE,
  INDEX `fk_usuario_rol_idx` (`rol_id` ASC) VISIBLE,
  INDEX `fk_usuario_multimedia1_idx` (`multimedia_id` ASC) VISIBLE,
  UNIQUE INDEX `multimedia_id_UNIQUE` (`multimedia_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_rol`
    FOREIGN KEY (`rol_id`)
    REFERENCES `tesis_db`.`rol` (`id`),
  CONSTRAINT `fk_usuario_multimedia1`
    FOREIGN KEY (`multimedia_id`)
    REFERENCES `tesis_db`.`multimedia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `tesis_db`.`estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tesis_db`.`estudiante` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ciclo` VARCHAR(45) NULL DEFAULT NULL,
  `fecha_nacimiento` DATE NULL DEFAULT NULL,
  `usuario_id` INT NOT NULL,
  `carrera` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_estudiante_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_estudiante_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `tesis_db`.`usuario` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `tesis_db`.`psicologo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tesis_db`.`psicologo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `especialidad` VARCHAR(100) NULL DEFAULT NULL,
  `usuario_id` INT NOT NULL,
  `descripcion` VARCHAR(245) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_psicologo_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_psicologo_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `tesis_db`.`usuario` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `tesis_db`.`calificaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tesis_db`.`calificaciones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `comentario` VARCHAR(245) NULL DEFAULT NULL,
  `fecha_creacion` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `psicologo_id` INT NOT NULL,
  `estudiante_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_calificaciones_estudiante1_idx` (`estudiante_id` ASC) VISIBLE,
  INDEX `fk_calificaciones_psicologo1_idx` (`psicologo_id` ASC) VISIBLE,
  CONSTRAINT `fk_calificaciones_estudiante1`
    FOREIGN KEY (`estudiante_id`)
    REFERENCES `tesis_db`.`estudiante` (`id`),
  CONSTRAINT `fk_calificaciones_psicologo1`
    FOREIGN KEY (`psicologo_id`)
    REFERENCES `tesis_db`.`psicologo` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `tesis_db`.`multimedia_actividad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tesis_db`.`multimedia_actividad` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(255) NULL DEFAULT NULL,
  `fecha` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `tesis_db`.`metodos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tesis_db`.`metodos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  `tipo` ENUM('recomendado', 'privado') NOT NULL,
  `psicologo_id` INT NOT NULL,
  `multimedia_actividad_id` INT NOT NULL,
  `estudiante_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_metodos_psicologo1_idx` (`psicologo_id` ASC) VISIBLE,
  INDEX `fk_metodos_multimedia_actividad1_idx` (`multimedia_actividad_id` ASC) VISIBLE,
  INDEX `fk_metodos_estudiante1_idx` (`estudiante_id` ASC) VISIBLE,
  CONSTRAINT `fk_metodos_psicologo1`
    FOREIGN KEY (`psicologo_id`)
    REFERENCES `tesis_db`.`psicologo` (`id`),
  CONSTRAINT `fk_metodos_multimedia_actividad1`
    FOREIGN KEY (`multimedia_actividad_id`)
    REFERENCES `tesis_db`.`multimedia_actividad` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_metodos_estudiante1`
    FOREIGN KEY (`estudiante_id`)
    REFERENCES `tesis_db`.`estudiante` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `tesis_db`.`pregunta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tesis_db`.`pregunta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `txt_pregunta` VARCHAR(250) NULL DEFAULT NULL,
  `tipo` ENUM('abierto', 'cerrada') NOT NULL,
  `psicologo_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pregunta_psicologo1_idx` (`psicologo_id` ASC) VISIBLE,
  CONSTRAINT `fk_pregunta_psicologo1`
    FOREIGN KEY (`psicologo_id`)
    REFERENCES `tesis_db`.`psicologo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `tesis_db`.`opciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tesis_db`.`opciones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `txt_opcion` VARCHAR(245) NULL DEFAULT NULL,
  `pregunta_id` INT NOT NULL,
  `psicologo_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_opciones_pregunta1_idx` (`pregunta_id` ASC) VISIBLE,
  INDEX `fk_opciones_psicologo1_idx` (`psicologo_id` ASC) VISIBLE,
  CONSTRAINT `fk_opciones_pregunta1`
    FOREIGN KEY (`pregunta_id`)
    REFERENCES `tesis_db`.`pregunta` (`id`),
  CONSTRAINT `fk_opciones_psicologo1`
    FOREIGN KEY (`psicologo_id`)
    REFERENCES `tesis_db`.`psicologo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `tesis_db`.`respuestas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tesis_db`.`respuestas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `pregunta_id` INT NOT NULL,
  `estudiante_id` INT NOT NULL,
  `opciones_id` INT NULL,
  `respuesta_texto` VARCHAR(245) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_respuestas_pregunta1_idx` (`pregunta_id` ASC) VISIBLE,
  INDEX `fk_respuestas_estudiante1_idx` (`estudiante_id` ASC) VISIBLE,
  INDEX `fk_respuestas_opciones1_idx` (`opciones_id` ASC) VISIBLE,
  CONSTRAINT `fk_respuestas_estudiante1`
    FOREIGN KEY (`estudiante_id`)
    REFERENCES `tesis_db`.`estudiante` (`id`),
  CONSTRAINT `fk_respuestas_opciones1`
    FOREIGN KEY (`opciones_id`)
    REFERENCES `tesis_db`.`opciones` (`id`),
  CONSTRAINT `fk_respuestas_pregunta1`
    FOREIGN KEY (`pregunta_id`)
    REFERENCES `tesis_db`.`pregunta` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `tesis_db`.`seguimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tesis_db`.`seguimiento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha_inicio` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_fin` TIMESTAMP NULL DEFAULT NULL,
  `estado` ENUM('pendiente', 'activo', 'finalizado') NULL DEFAULT 'pendiente',
  `estudiante_id` INT NOT NULL,
  `psicologo_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_seguimiento_estudiante1_idx` (`estudiante_id` ASC) VISIBLE,
  INDEX `fk_seguimiento_psicologo1_idx` (`psicologo_id` ASC) VISIBLE,
  CONSTRAINT `fk_seguimiento_estudiante1`
    FOREIGN KEY (`estudiante_id`)
    REFERENCES `tesis_db`.`estudiante` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_seguimiento_psicologo1`
    FOREIGN KEY (`psicologo_id`)
    REFERENCES `tesis_db`.`psicologo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `tesis_db`.`google_tokens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tesis_db`.`google_tokens` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `access_token` VARCHAR(255) NULL DEFAULT NULL,
  `refresh_token` VARCHAR(255) NULL DEFAULT NULL,
  `psicologo_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_google_tokens_psicologo1_idx` (`psicologo_id` ASC) VISIBLE,
  CONSTRAINT `fk_google_tokens_psicologo1`
    FOREIGN KEY (`psicologo_id`)
    REFERENCES `tesis_db`.`psicologo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `tesis_db`.`cita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tesis_db`.`cita` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `fecha_inicio` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_fin` TIMESTAMP NULL DEFAULT NULL,
  `evento_google_id` VARCHAR(245) NULL,
  `estado` ENUM('pendiente', 'aceptada', 'rechazada', 'cancelada', 'realizada') NULL DEFAULT 'pendiente',
  `creado_por` ENUM('estudiante', 'psicologo') NULL DEFAULT 'estudiante',
  `estudiante_id` INT NOT NULL,
  `psicologo_id` INT NOT NULL,
  `seguimiento_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cita_estudiante1_idx` (`estudiante_id` ASC) VISIBLE,
  INDEX `fk_cita_psicologo1_idx` (`psicologo_id` ASC) VISIBLE,
  INDEX `fk_cita_seguimiento1_idx` (`seguimiento_id` ASC) VISIBLE,
  CONSTRAINT `fk_cita_estudiante1`
    FOREIGN KEY (`estudiante_id`)
    REFERENCES `tesis_db`.`estudiante` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cita_psicologo1`
    FOREIGN KEY (`psicologo_id`)
    REFERENCES `tesis_db`.`psicologo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cita_seguimiento1`
    FOREIGN KEY (`seguimiento_id`)
    REFERENCES `tesis_db`.`seguimiento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `tesis_db`.`disponibilidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tesis_db`.`disponibilidad` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dia` ENUM('lunes', 'martes', 'miercoles', 'jueves', 'viernes') NOT NULL,
  `hora_inicio` TIME NULL,
  `hora_fin` TIME NULL,
  `turno` ENUM('temprano', 'tarde') NOT NULL,
  `psicologo_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_disponibilidad_psicologo1_idx` (`psicologo_id` ASC) VISIBLE,
  CONSTRAINT `fk_disponibilidad_psicologo1`
    FOREIGN KEY (`psicologo_id`)
    REFERENCES `tesis_db`.`psicologo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

use tesis_db;
INSERT INTO tesis_db.rol (id, nombre) VALUES (1, 'psicologo'), (2, 'estudiante'), (3,'administrador');
use tesis_db;
insert into multimedia (id,url) values (1,'img');
use tesis_db;
INSERT INTO usuario (nombre, correo, apellido, rol_id, multimedia_id, contrasena)
VALUES ('Admin', 'admin@tecsup.edu.pe', 'Dev', 3, 1, '$2a$12$ePuP88Su.ysbxTrUpt01ouxeohyH3UK0f0aVAOHLA9wJhM269nxuq');