name: frondend
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  video_player: ^2.7.0
  shared_preferences: ^2.5.3
  google_sign_in: ^6.1.5

  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.4
  flutter_launcher_icons: ^0.14.3
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/logologin.png
    - assets/logologin2.png
    - assets/images/superior.png
    - assets/google_icon.png
    - assets/icon/logoi.png 
    - assets/images/default_user.png
flutter_native_splash:
  color: "#2196F3" 
  image: assets/logo.png 
  android: true
  ios: true
  web: false
  fullscreen: true


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/logoi.png"
